# Generated by Django 4.2.13 on 2024-07-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="event_scheduler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("description", models.TextField()),
            ],
        ),
    ]
